In [5]:
import pandas as pd 
import numpy as np

In [6]:
baseDados = [
    9.20, 9.30, 9.40, 9.50, 9.60, 9.60, 9.70, 9.70, 9.80, 9.80,  9.90, 10.10, 10.30,
    9.20, 9.30, 9.40, 9.50, 9.60, 9.60, 9.70, 9.70, 9.80, 9.80,  9.90, 10.10, 10.30,
    9.20, 9.30, 9.40, 9.50, 9.60, 9.60, 9.70, 9.70, 9.80, 9.90,  9.90, 10.10, 10.30,
    9.20, 9.40, 9.40, 9.50, 9.60, 9.60, 9.70, 9.70, 9.80, 9.90, 10.00, 10.10, 10.40,
    9.20, 9.40, 9.40, 9.50, 9.60, 9.60, 9.70, 9.70, 9.80, 9.90, 10.00, 10.20, 10.40,
    9.30, 9.40, 9.50, 9.50, 9.60, 9.60, 9.70, 9.70, 9.80, 9.90, 10.00, 10.20,
    9.30, 9.40, 9.50, 9.50, 9.60, 9.60, 9.70, 9.80, 9.80, 9.90, 10.00, 10.20,
    9.30, 9.40, 9.50, 9.50, 9.60, 9.70, 9.70, 9.80, 9.80, 9.90, 10.00, 10.20,
    9.30, 9.40, 9.50, 9.60, 9.60, 9.70, 9.70, 9.80, 9.80, 9.90, 10.00, 10.20,
    9.30, 9.40, 9.50, 9.60, 9.60, 9.70, 9.70, 9.80, 9.80, 9.90, 10.00, 10.30,
]

In [92]:
baseDados.sort()
serie = pd.Series(baseDados)

df = pd.DataFrame(serie.value_counts().sort_index())
df = df.reset_index()
df.columns = ['xi','fi']
total = df['fi'].sum()

freq_acumulada = []
acumulada = 0 
for frequencia in df['fi']:
    acumulada = acumulada + frequencia
    freq_acumulada.append(acumulada)

df['Fi'] = freq_acumulada
df['Fi %'] = df['Fi'] / total
df['xifi'] = df['xi'] * df['fi']
df['xi2fi'] = (df['xi'] ** 2) * df['fi']

df['filnxi'] = df['fi'] * np.log(df['xi'])
df['fi/xi'] = df['fi'] / df['xi']
df

      xi  fi   Fi   Fi %   xifi    xi2fi     filnxi     fi/xi
0    9.2   5    5  0.040   46.0   423.20  11.096017  0.543478
1    9.3   8   13  0.104   74.4   691.92  17.840115  0.860215
2    9.4  12   25  0.200  112.8  1060.32  26.888516  1.276596
3    9.5  13   38  0.304  123.5  1173.25  29.266793  1.368421
4    9.6  19   57  0.456  182.4  1751.04  42.973499  1.979167
5    9.7  19   76  0.608  184.3  1787.71  43.170392  1.958763
6    9.8  16   92  0.736  156.8  1536.64  36.518118  1.632653
7    9.9  11  103  0.824  108.9  1078.11  25.217882  1.111111
8   10.0   7  110  0.880   70.0   700.00  16.118096  0.700000
9   10.1   4  114  0.912   40.4   408.04   9.250142  0.396040
10  10.2   5  119  0.952   51.0   520.20  11.611939  0.490196
11  10.3   4  123  0.984   41.2   424.36   9.328576  0.388350
12  10.4   2  125  1.000   20.8   216.32   4.683612  0.192308

In [93]:
media = (1 / total) * df['xifi'].sum()
mediaGeometrica = np.e ** ((1/total) * df['filnxi'].sum())
mediaHarmonica = total / (df['fi/xi'].sum())
mediaQuadratica = np.sqrt(df['xi2fi'].sum()/total)


print('Media Aritmetica: ', np.round(media,4))
print('Media Geometrica: ', np.round(mediaGeometrica,4))
print('Media Harmonica: ', np.round(mediaHarmonica,4))
print('Media Quadratica: ', np.round(mediaQuadratica,4))

Media Aritmetica:  9.7
Media Geometrica:  9.696
Media Harmonica:  9.692
Media Quadratica:  9.7041

In [94]:
k = 97.5
i = int(k/100 * (total + 1))

xi = baseDados[i -1]
xii =baseDados[i]

pk = xi + ((k/100 * (total + 1)) - i) * (xii - xi)
print(pk)
print(np.percentile(baseDados, k))

10.3
10.3

In [95]:
maximo = df['fi'].max()

moda = df['xi'].loc[df['fi'] == maximo]
moda

4    9.6
5    9.7
Name: xi, dtype: float64